import type { Catalog, Item, JobClass, Stats } from '../shared/types.js';
export const ones: Stats = { str: 1, agi: 1, vit: 1, int: 1, dex: 1, luk: 1 };
const sprite = { spr: 'test.spr', act: 'test.act' };
const item = (id: number, overrides: Partial<Item>): Item => ({ id, name: `Item ${id}`, aegisName: `${id}`, type: 'loot', attack: 0, def: 0, slots: 0, minLevel: 1, allowedClasses: [], buyPrice: 10, sellPrice: 5, weight: 1, resource: 'test', effects: {}, shop: true, ...overrides });
const job = (id: string, overrides: Partial<JobClass>): JobClass => ({ id, name: id, family: id, tier: 1, trans: false, minJobLevel: 10, weapons: ['dagger'], skills: ['firstaid'], jobCap: 50, expGroup: 'normal', hp: Array(99).fill(100), sp: Array(99).fill(50), sprite: { male: sprite, female: sprite }, ...overrides });
export function fixture(): Catalog {
  return {
    version: 'test', source: { commit: 'test', files: [], hash: 'test' }, rates: { baseExp: 4, jobExp: 4, drop: 1 },
    monsters: { 1002: { id: 1002, name: 'Poring', aegisName: 'PORING', sprite, level: 1, hp: 50, attack: [1, 1], def: 0, mdef: 0, stats: { ...ones }, baseExp: 2, jobExp: 1, attackDelay: 2000, element: 'Water', elementLevel: 1, size: 'Medium', race: 'Plant', drops: [{ itemId: 909, chance: 10000 }] } },
    items: { 1201: item(1201, { type: 'equipment', slot: 'weapon', weaponType: 'dagger', attack: 20, slots: 2 }), 2301: item(2301, { type: 'equipment', slot: 'armor', def: 1, slots: 1 }), 501: item(501, { type: 'consumable', healHP: 45 }), 505: item(505, { type: 'consumable', healSP: 40 }), 909: item(909, {}), 984: item(984, { type: 'material' }), 985: item(985, { type: 'material' }), 4001: item(4001, { type: 'card', cardSlots: ['armor'], effects: { luk: 2 } }), 1701: item(1701, { type: 'equipment', slot: 'weapon', weaponType: 'bow', attack: 20, allowedClasses: ['archer', 'hunter', 'sniper'] }) },
    classes: { novice: job('novice', { tier: 0, family: 'novice', jobCap: 10, minJobLevel: 0 }), high_novice: job('high_novice', { tier: 0, family: 'novice', trans: true, jobCap: 10, minJobLevel: 0 }), swordsman: job('swordsman', { parent: 'novice', family: 'swordsman' }), knight: job('knight', { parent: 'swordsman', family: 'swordsman', tier: 2, minJobLevel: 40 }), lord_knight: job('lord_knight', { parent: 'swordsman', family: 'swordsman', tier: 2, trans: true, minJobLevel: 40, jobCap: 70 }), archer: job('archer', { parent: 'novice', family: 'archer', weapons: ['bow'] }), hunter: job('hunter', { parent: 'archer', family: 'archer', tier: 2, minJobLevel: 40, weapons: ['bow'] }), sniper: job('sniper', { parent: 'archer', family: 'archer', tier: 2, trans: true, minJobLevel: 40, weapons: ['bow'], jobCap: 70 }), mage: job('mage', { parent: 'novice', family: 'mage', skills: ['firstaid', 'firebolt'], weapons: ['staff', 'dagger'] }) },
    skills: { firstaid: { id: 'firstaid', name: 'Primeiros Socorros', description: '', kind: 'heal', maxLevel: 1, spCost: [3], power: [20], cooldownMs: 3000 }, firebolt: { id: 'firebolt', name: 'Lanças de Fogo', description: '', kind: 'magical', maxLevel: 10, spCost: Array(10).fill(5), power: Array(10).fill(150), cooldownMs: 3000, element: 'Fire' } },
    areas: [{ id: 'prontera', name: 'Prontera', map: 'prt_fild08', minLevel: 1, description: '', monsters: [1002], scene: 'field' }, { id: 'locked', name: 'Locked', map: '', minLevel: 65, description: '', monsters: [1002], scene: 'castle' }],
    quests: [{ id: 'firstkill', name: 'Primeiro abate', description: '', kind: 'kills', target: 1002, amount: 1, reward: { zeny: 100, baseExp: 0, jobExp: 0, items: [] } }],
    challenges: [{ id: 'mastering', name: 'Mastering', monsterId: 1002, minLevel: 15, cooldownMs: 3600000, timeoutMs: 600000, firstReward: { zeny: 1000, baseExp: 0, jobExp: 0, items: [] } }],
    exp: { base: [0, ...Array(99).fill(100)], job: { normal: [0, ...Array(70).fill(40)] } },
  };
}
