import type { Catalog } from '../../../shared/types';
import type { RankingPage } from '../../../shared/portal-types';
import { formatNumber, LoadState, Panel, usePublicData } from '../PortalShell';
import { navigate, useRoute } from '../router';
export default function Ranking() {
  const { search } = useRoute(); const query = new URLSearchParams(search); const rawCategory = query.get('category'); const category = rawCategory === 'zeny' || rawCategory === 'kills' ? rawCategory : 'level'; const classId = query.get('class') ?? 'all'; const rawPage = Number(query.get('page')); const page = Number.isSafeInteger(rawPage) && rawPage > 0 ? rawPage : 1;
  const catalog = usePublicData<Catalog>('/api/catalog'); const ranking = usePublicData<RankingPage>(`/api/portal/ranking?category=${category}&class=${encodeURIComponent(classId)}&page=${page}`);
  const change = (next: { category?: string; classId?: string; page?: number }) => navigate(`/ranking?category=${next.category ?? category}&class=${encodeURIComponent(next.classId ?? classId)}&page=${next.page ?? 1}`);
  return <><h1>Ranking de aventureiros</h1><Panel title="O salão dos heróis"><p>Personagens das contas do Idle, classificados pelo último progresso salvo.</p><div className="portal-filters"><label>Classificar por<select name="category" value={category} onChange={event => change({ category: event.target.value })}><option value="level">Nível</option><option value="zeny">Zeny</option><option value="kills">Abates</option></select></label><label>Classe<select name="class" value={classId} disabled={!catalog.data} onChange={event => change({ classId: event.target.value })}><option value="all">Todas as classes</option>{catalog.data && Object.values(catalog.data.classes).map(job => <option key={job.id} value={job.id}>{job.name}</option>)}</select></label></div>
    {catalog.error && <LoadState error={catalog.error} retry={catalog.retry} />}
    {ranking.data ? <>{ranking.data.rows.length ? <div className="portal-table-scroll" tabIndex={0} role="region" aria-label="Classificação dos aventureiros"><table><thead><tr><th scope="col">Posição</th><th scope="col">Personagem</th><th scope="col">Classe</th><th scope="col">Base / Job</th><th scope="col">{category === 'zeny' ? 'Zeny' : category === 'kills' ? 'Abates' : 'Nível Base'}</th></tr></thead><tbody>{ranking.data.rows.map(row => <tr key={row.rank}><td className="portal-rank-cell">{row.rank}º</td><th scope="row">{row.characterName}{row.reborn && <small>Renascido</small>}</th><td>{catalog.data?.classes[row.classId]?.name ?? row.classId}</td><td>{row.baseLevel} / {row.jobLevel}</td><td>{formatNumber(row.value)}</td></tr>)}</tbody></table></div> : <p className="portal-empty">Ainda não há aventureiros classificados para estes filtros.</p>}<div className="portal-pagination"><button disabled={page <= 1} onClick={() => change({ page: page - 1 })}>Anterior</button><span>Página {page} de {Math.max(1, Math.ceil(ranking.data.total / ranking.data.pageSize))}</span><button disabled={page * ranking.data.pageSize >= ranking.data.total} onClick={() => change({ page: page + 1 })}>Próxima</button></div><p className="portal-muted">Consulta em {new Date(ranking.data.updatedAt).toLocaleString('pt-BR')}. O ranking não atualiza o tempo de caça.</p></> : <LoadState {...ranking} />}
  </Panel></>;
}
