import { resolve } from 'node:path';
import { createPool } from 'mysql2/promise';
import { createInitialState } from '../engine/index.js';
import { loadCatalog } from './catalog.js';
import { GameRepository, migrate, resolveLegacyProfileId } from './repository.js';
import { buildApp } from './app.js';
import { MysqlChatRepository } from './chat.js';
import { SqlAccountStore } from './identity/repository.js';
import { SqlGameProfiles } from './profiles.js';
import { createScheduler } from './scheduler.js';
import { SqlPortalQueries } from './portal/repository.js';

const catalog = await loadCatalog();
const pool = createPool({ host: process.env.DB_HOST ?? 'database', port: Number(process.env.DB_PORT ?? 3306), user: process.env.DB_USER, password: process.env.DB_PASSWORD, database: process.env.DB_NAME, connectionLimit: 6, charset: 'utf8mb4' });
await migrate(pool);
const legacyProfileId = await resolveLegacyProfileId(pool);
const repository = new GameRepository(pool, () => createInitialState(catalog, Date.now(), 'djow'), legacyProfileId);
await repository.read();
const profiles = new SqlGameProfiles(pool);
const accounts = new SqlAccountStore(pool);
const allowedOrigins = process.env.RAGIDLE_ALLOWED_ORIGINS?.split(',').map(origin => origin.trim()).filter(Boolean);
const app = await buildApp({ catalog, accounts, profiles, portal: new SqlPortalQueries(pool), chatRepository: new MysqlChatRepository(pool), now: Date.now, publicOrigin: process.env.PUBLIC_ORIGIN, allowedOrigins, assetOrigin: process.env.ASSET_ORIGIN, webRoot: resolve('public-build') });
const scheduler = createScheduler({ profiles, catalog, now: Date.now, reportError: profileId => { console.error(`Não foi possível salvar o progresso idle (${profileId}).`); } });
scheduler.start();
app.addHook('onClose', async () => { await scheduler.stop(); await pool.end(); });
await app.listen({ host: '0.0.0.0', port: Number(process.env.PORT ?? 3339) });
console.info('Ragnarok Old Times Idle disponível na porta 3339.');
for (const signal of ['SIGINT', 'SIGTERM'] as const) process.once(signal, () => { void app.close(); });
